### ISSUE TITLE
Sanity checker should not abort stimulus_reflex install task

### ISSUE THREAD

**Issue by leastbad** [stimulusreflex/stimulus_reflex#508]
# Bug Report

## Describe the bug

Upon running `rake stimulus_reflex:install`, the sanity checker module aborts with the message about: "StimulusReflex strongly suggests that you set default_url_options in your environment files."

## Expected behavior

This shouldn't happen.

### StimulusReflex

- Gem: 3.5.0.pre0
- Node package: 3.5.0-pre0

**Comment by RolandStuder** [comment]
@leastbad maybe I will have some time to tackle this until Friday.

**Comment by marcoroth** [comment]
Hey @RolandStuder, check out the comment here: https://github.com/stimulusreflex/stimulus_reflex/pull/510#discussion_r637619224

Maybe you can still help to get this sorted, thank you!

**Comment by leastbad** [comment]
I'm not 100% confident that my solution is the best solution. In fact, it's a total hack - I'm plagued by the feeling that there's an obvious way to do this that just isn't landing. I would have 100% assumed the `ARGV` thing would work, but as wild as it seems there's no apparent way to retrieve the command that executed the current process.

Actively hoping someone steps in with a clever take.
