### ISSUE TITLE
How to (better) use Stimulus Reflex with Cypress?

### ISSUE THREAD

**Issue by mleszcz** [stimulusreflex/stimulus_reflex#512]
We use SR in our Rails app. We use cypress as e2e testing framework.
Cypress doesn't handle action cable's requests. We had to handle it manually like this:
```
# application.html.erb
  <body data-leftbar-theme="dark" data-reflexes="0" data-controller="selectpicker">

# application_controller.js
  beforeReflex(element, reflex, noop, reflexId) {
    let reflexes = parseInt(document.body.getAttribute('data-reflexes'));
    reflexes++;
    document.body.setAttribute('data-reflexes', reflexes);
  }

  finalizeReflex(element, reflex, noop, reflexId) {
    let reflexes = parseInt(document.body.getAttribute('data-reflexes'));
    reflexes--;
    document.body.setAttribute('data-reflexes', reflexes);
  }

# commands.js
Cypress.Commands.add('reflex', () => {
  cy.get('body').should('have.attr', 'data-reflexes', '0').wait(50)
})

# then in the tests when some user action triggers reflex request we have to:
cy.contains('Next').click().reflex()
```

That works pretty good. 

1. We'd like to check if there any other (better) way to handle SR in Cypress?
2. If NO :) then we'd like to improve above `reflex` method and somehow get rid of `wait(50)`. The reason it's there is that it turned out that when finalizeReflex got triggered sometimes DOM isn't ready yet. Maybe there's some other even triggered after reflex is finalized and the whole DOM regenerated?

**Comment by leastbad** [comment]
Hi Mateusz! This is a valid concern, but it's not an *issue*.

This seems like something worth discussing on [Discord](https://discord.gg/stimulus-reflex), no?
