### ISSUE TITLE
The ActionCable channel subscription for StimulusReflex gets rejected when interacting too fast 

### ISSUE THREAD

**Issue by Danilodum** [stimulusreflex/stimulus_reflex#539]
I'm looking for some pointers on how to solve the following error from occurring when users interact with the page too fast after load

```
Error invoking action "click->stimulus-reflex#__perform"

 The ActionCable channel subscription for StimulusReflex was rejected. 
```

Where do I look for the cause of the rejection, can I implement retries on the client or something?

**Comment by leastbad** [comment]
Hello, Danilo!

We provide 24/7 support via [Discord](https://discord.gg/stimulus-reflex), where we'd be happy to talk you through this.

GH Issues is not a support channel. 💙

**Comment by leastbad** [comment]
@Danilodum I just wanted to check in because I don't know your Discord handle if you have one.

We don't want to leave you hanging, just not to use Issues to ask for help with your app.

**Comment by Danilodum** [comment]
❤️

I connected with jonathan-s/argparse about this in the sockpuppet channel, still working on getting him a repro, I think I'm in good hands, thank you
