### ISSUE TITLE
Do not import controllers in installer when already present

### ISSUE THREAD

**Issue by julianrubisch** [stimulusreflex/stimulus_reflex#544]
# Bug Report

## Describe the bug

The installer might add an additional `import "controllers"` in `app/javascript/packs/application.js` when one is already present.

## Expected behavior

There should be no duplicate imports.

**Comment by leastbad** [comment]
Could you explain further? Is there a line number?

**Comment by julianrubisch** [comment]
I‘ll close this because the new installer should cover it #610
