### ISSUE TITLE
Rails 7 Alpha Incompatibility

### ISSUE THREAD

**Issue by omairrazam** [stimulusreflex/stimulus_reflex#552]
I had a fresh Rails 7 Alpha install - when i ran the server I faced this error `Uncaught TypeError: Failed to resolve module specifier "stimulus_reflex". Relative references must start with either "/", "./", or "../".`

I was using default import_maps feature of rails that is a replacement of webpacker. It seems like Stimulus reflex is not compatible with latest Rails version.

I used this blog to setup a fresh Rails 7 Alpha install.
https://rajeevkannav.com/post/2021-03-19-install-rails7-alpha-edge/

I created new rails application with this command.
`bundle exec rails new app_name --dev --css tailwind`

**Comment by leastbad** [comment]
Hi Omair,

Rails 7 is in **alpha**, and the bundling ecosystem is in massive flux. While chasing the bleeding edge can be exciting, when you're supporting a large number of production applications, we owe it to our users to be extremely careful and thorough.

StimulusReflex will support all of the Rails 7 bundling options shortly after it launches.

In the meantime, we recommend that you use Webpacker 5.4.3 with Rails 6.1 to build apps with StimulusReflex. You can install SR/CR into a `rails new` app with a single command.

Please feel free to [jump on Discord](https://discord.gg/stimulus-reflex) if you would like to discuss further.

**Comment by ricvillagrana** [comment]
Any news on this @leastbad?
I gave StimulusReflex a try and got the same error.

Thanks in advance, this is an awesome project!

**Comment by marcoroth** [comment]
@ricvillagrana thanks for reaching out! This should be resolved with the 3.5 pre-releases/RCs. Can you make sure you are using `3.5.0.rc2`? Thank you!
