### ISSUE TITLE
2 Issues: Nonexistent Cable Ready operation selectors / data-reflex shorthand 

### ISSUE THREAD

**Issue by pooriar** [stimulusreflex/stimulus_reflex#557]
# Bug Report

## Describe the bug

Found 2 bugs while pairing with @marcoroth 
1. If a reflex contains multiple CableReady operations and *some* of the operations have element selectors that don't exist on the page, then *none* of the operations in that reflex set will run.
2. The shorthand that lets you omit the `click->` in `click->Reflex#action` on buttons doesn't work. Leaving out the `click->` causes the action to not fire off.

## To Reproduce

Clone [this repo](https://github.com/pooriar/stimulus-reflex-issue-example), start the server, click the buttons on the root url

## Expected behavior

All 3 buttons should work based on stimulus reflex expectations

### StimulusReflex

- Gem: 3.5.0.pre6
- Node package: 3.5.0-pre6

### External tools

- Ruby: 2.7
- Rails: 6.1.4.1

**Comment by marcoroth** [comment]
The first issue was resolved in `3.5.0-pre6` and the Stimulus shorthand for `data-reflex` attributes isn't going to be implemented. Therefore I'm going to close this issue for now.
