### ISSUE TITLE
Reflex modifying ActionDispatch::Request before Rails Controller is instantiated 

### ISSUE THREAD

**Issue by nakwa** [stimulusreflex/stimulus_reflex#570]
# Feature Request

It'd be useful for reflexes to being able to alter/update the [ActionDispatch request env](https://github.com/stimulusreflex/stimulus_reflex/blob/master/lib/stimulus_reflex/reflex.rb#L82) (that is URL, HEADERS or at least QueryString) before instantiating the Rails Controllers (when going with morph :page).

## Is your feature request related to a problem?

Sometimes reflexes will update the browser history/URL, through the use of action_cable `push_state`. While the URL is updated client-side (browser history), ActionDispatch::Request will be instantiated with a mocked environment which will in turn be used to instantiate the Rails Controller and will be available in the controller action. 

If for any reason the reflex needs to alter the request (update some params, headers, ...), these are not made available or reflected in any middleware nor in the controller action.

This is impractical, for example in case where the controller method is making use of the request object, which you may want to modify beforehand in the reflex method. For instance, imagine a controller rendering a template with a helper to generate URLs derived from the current `request.fullpath` params and combining it with new ones. If you have updated the browser history state (with `push_state`), you'd expect this to be reflected in the `request` object available in the controller action as well. 

## Describe the solution you'd like

I guess there could be a setter method to update/merge/replace parts of the request env (querystring, path, headers)...

Right now, for some reason (no doubt it's a valid one), the ActionDispatch::Request object is instantiated directly with the reflex (i.e. [`initialize`](https://github.com/stimulusreflex/stimulus_reflex/blob/master/lib/stimulus_reflex/reflex.rb#L23) calls [`param`](https://github.com/stimulusreflex/stimulus_reflex/blob/master/lib/stimulus_reflex/reflex.rb#L52) which calls [`request.parameters`](https://github.com/stimulusreflex/stimulus_reflex/blob/master/lib/stimulus_reflex/reflex.rb#L82), which consequently calls the request method). 

Two scenario: 
* If the request object doesn't really need to be instantiated before the reflex itself is processed, maybe we could make sure that this method is only called at the time where the controller is being called (that is, after the reflex was executed). 
* Otherwise maybe it'd be possibly to have a distinction between "previous_request" env and "next_request" env ? 

Of course I may be unaware of the consequences of tempering with the request object, but from the 'use case' perspective I believe it'd make sense to being able to alter the request object before handing things over to the controller. 

## PR link

Just an idea. Eager to get some feedback.

**Comment by leastbad** [comment]
Thanks for this!

I hear you on all points. You are not at all crazy. Yes, it is very complicated. This functionality touches most of the most Jenga aspects of the library, and there's a non-trivial number of bugs that have been fixed, edge cases that have been accounted for and of course, people relying on the library to behave in a certain way.

It's especially complicated by the fact that developers can define `before_reflex` callbacks. It is further complicated by how incredibly tricky it is to dynamically create an Action Controller instance that doesn't have something Off about it, running inside of an Action Cable connection context.

I will take issue with your phrasing of "This is impractical" because I will point out that the status quo has been really solid for many thousands of developers for several years, but there's always room for improvement... especially when new blood rolls up their sleeves and learns the codebase. 😉 

Anyhow, I'd like you to check out #538 and #542, and let me know if these either address your needs or inspire you to propose further accessors such as #538's `self.headers`. PRs welcome!

**Comment by nakwa** [comment]
Thanks for your reply @leastbad.
So I've been experimenting a little on how to make this work. 

- Attempt 1: Updating the request object path and params,  just like it is done with headers in #538. Bottom line is that, as far as I understand, it isn't possible to simply update the request object with a new path. It may be possible to [update the params](https://github.com/Rails/Rails/blob/main/actionpack/lib/action_dispatch/http/request.rb#L416), but the request object is instantiated with a URI that later can't be changed - so it doesn't solve anything in case where something in the controller/templates relies on request.fullpath. 

- Attempt 2: Instead of instantiating directly an ActionDispatch::Request in reflex#request, there may be a new SteroidsReflex::Request object, inheriting from ActionDispatch::Request, and tweaking it/overriding it in a way that makes it updatable. I did not spent much time looking at this, because this would obviously have a lot of caveats and like you said, no doubt it is already tricky enough to create an ActionDispatch::Request ActionController that doesn't have something off about it.

- Attempt 3: A request object is instantiated and available with the reflex (just like now), and another entirely new request object is created for the purpose of instantiating the Action Controller. That way it leaves developper the full ability to tweak any part of the context (headers, params, path) in their reflex and the controller is created the an updated request object. Downside: (1) ActionDispatch::Request instantiation happens twice, (2) Possible issue for any library that would be looking at the ActionDispatch::Request instance/object_id - since there are now two distinct objects ? 
That would look something like this: https://github.com/nakwa/stimulus_reflex/pull/1/files

Thoughts?

**Comment by nakwa** [comment]
Understood. StimulusReflex is meant to dynamically update stuff on the current page, I get it, it makes sens. 
I also understand that CableReady push_state and other operations are not of stimulus reflex concern, in any way.

Nonetheless, in the same way that you can change `headers` and assign `params` shouldn't it be possible to update the query part of the URL (`querystring` parameters) accordingly ? While I agree updating the `path` itself is outside the scope of SR, I was merely trying to enable changing the querystring part of the URL and to have it reflected in ActionDispatch::Request `fullpath`. 

In other worlds: is `https://app.foo.com/bar?baz=123` really to be considered a different page than `https://app.foo.com/bar?baz=456` - and should navigating from one to the other justify the use of cable_ready.redirect_to, acknowledging that this comes with its own set of downsides? 

Of course, I do understand that, pragmatically, given the complexity of emulating ActionDispatch::Request, what I was suggesting may simply be too "expensive", compare to the edge-case need for it, also considering that there are workaround.

Anyway. Thanks for suggesting ways around this.
I have joined the Discord channel. Apologies if this was not the place for this kind of discussion.
