### ISSUE TITLE
`StimulusReflex.config.logging = nil` raises errors

### ISSUE THREAD

**Issue by ni3t** [stimulusreflex/stimulus_reflex#574]
# Bug Report

## Describe the bug

Setting `config.logging` (the [documented way](https://docs.stimulusreflex.com/appendices/troubleshooting#stimulusreflex-logging) to kill logging on the server) to nil raises errors when logging.

## To Reproduce

Set `config.logging` to nil and see these errors:

```
NoMethodError: private method `binding' called for nil:NilClass
Did you mean?  __binding__
  from stimulus_reflex (3.5.0.pre8) lib/stimulus_reflex/utils/logger.rb:30:in `config_logging'
```

## Expected behavior

Not throw errors

## Screenshots or reproduction

n/a

### StimulusReflex

- Gem: 3.5.0.pre8
- Node package: 3.5.0.pre8

### External tools

- Ruby: 3.0.3
- Rails: 6.1.4.1
- Node: 16.14.0

### Browser

n/a

**Comment by leastbad** [comment]
Great catch, Nick! **Thank you**.
