### ISSUE TITLE
Add example with locales to documentation

### ISSUE THREAD

**Issue by Anakin100100** [stimulusreflex/stimulus_reflex#578]
# Feature Request

Add example with locales to documentation

## Is your feature request related to a problem?

The way that instance variables are passed to rendering partials are non obvious to new users and the error messages resulting don't point toward a solution at all (No route matches {} when model instance variable for a form is missing). 

## Describe the solution you'd like

adding an example with sth like

@articles = current_user.articles
 morph "#main_content", render(partial: "articles/list_all_articles", locals: { articles: @articles })

## Additional context

I didn't know how to approach this problem and wasted about an hour looking for a solution. After that in a shower it dawned on me that maybe something could be passed the render method. If I didn't come up with that I would have never been able to pass instance variables to partials for morphing page elementes. Overall I'm stunned by how well documented and amazing this project is.

**Comment by leastbad** [comment]
Hi Pawel, I'm glad that you got sorted out.

The first thing you should do in a situation where something is evading you is ask for help on Discord. We really are happy to answer questions like this. We don't want you to have to take a long walk and question your life.

One thing newcomers to Rails complain about is "magic". As a long-term Rails user, it only gets harder to be conscious of where magic is happening. One such example is the way controller action methods work: there's an implicit `render` that gets called unless you call it first, and the `render` that is default in a controller action is already primed with a whole bunch of extra data that you'd need to supply yourself if you call it directly.

The takeaway is that when it comes to those controller actions, they are logically tied to the eventual render that is going to happen. The magic is such that they are effectively *the same thing*. What is a controller action but foreplay leading to the main act, after all?

Whereas in SR, the `morph` method is ultimately accepting a string parameter, and it doesn't care how it's generated. Moreover, there might not be a `render` method call; there also could be several `render` method calls, if you're morphing several things. Your Nothing Morph might not do anything visual or impact the DOM at all - this is common when launching Active Jobs, for example.

What this means is that a Reflex method is *not* 1:1 with a `render` call, so the variables that in scope are not passed to `render` automatically. Now, there is some discussion of all this in the section https://docs.stimulusreflex.com/rtfm/morph-modes#intelligent-defaults but a lot of work has been done to perfect the `render` method that's available inside of a Reflex in the upcoming v3.5 release. I happen to agree with you that a simple explanation of the `morph` method and how it works with `render` would be a big deal. Thanks for the suggestion.
