### ISSUE TITLE
Reflex action happens twice when clicking once on a button with a Stimulus controller

### ISSUE THREAD

**Issue by wheee** [stimulusreflex/stimulus_reflex#605]
# Bug Report

## Describe the bug

Clicking on a Button with a reflex action and a stimulus controller fires the reflex action twice! 

## To Reproduce

1. Clone the repo and setup - bin/setup
2. Run the server - bin/rails s
3. Open localhost:3000 with Chrome (see note below about Safari)
4. Click on the button (or the link)
5. Observe in the DevTools console or in the Server logs that the ExampleReflex#poke is called twice

### Additional notes:
* If you go to the test_controller.js, and uncomment the connect() method, then the double-fire does not happen.
* BUT if you do have connect() uncommented, then the clientside lifecycle callbacks don't fire!  (ie. beforePoke) _**second bug!**_

### Note about Safari:
* Upon refreshing the page, the button doesn't actually work, whereas the link does (after a couple of seconds)
* Interestingly, once the link fires the reflex action, the button works
* Maybe I should create another bug for this?

## Expected behavior

* Should only fire the reflex once!
* Also, the clientside lifecycle callbacks (ie. beforePoke) should fire if connect() is specified.

## Screenshots or reproduction

Link to repo: https://github.com/wheee/double-reflex-fire-importmap
(Repo was originally a clone of https://github.com/marcoroth/stimulus_reflex-importmaps)

![image](https://user-images.githubusercontent.com/516324/187349059-c2920f5e-a226-4582-83c2-cfc30fbb7b8c.png)

## Workaround

Add a connect() method to the Stimulus controller.  Doesn't even have to do anything.

### StimulusReflex

- Gem: 3.5.0

### External tools

- Ruby: 3.1.2
- Rails: 7.0.2

### Browser

- Browser: Chrome
- Version: 104.0.5112.101 (Official Build) (arm64)

**Comment by marcoroth** [comment]
Hey @wheee, I just realized that I always just replied on Discord and not here. 

This issue is being resolved as soon as #606 is merged! Thank you!
