### ISSUE TITLE
`stimulus-reflex:ready` event should only be emitted once per page load

### ISSUE THREAD

**Issue by leastbad** [stimulusreflex/stimulus_reflex#608]
# Feature Request

Currently, the `stimulus-reflex:ready` event is emitted every time `setupDeclarativeReflexes()` is called. There are two concerns:

1. Someone might reasonably expect this to only be called once, leading to multiple initializations of app-level functions.
2. We might eventually remove the `readystatechange` handler in favour of just letting each Stimulus controller register itself... which means that calling the event when importmaps are in play could cause the event to fire before the controllers are actually ready.

## Is your feature request related to a problem?

Ties into the solution provided by #606.

## Describe the solution you'd like

The simple approach is to use a variable to track whether the event has been emitted, and then `return` if it's about to be emitted again. The complex approach - which I don't have a solution for due to my relative inexperience with importmaps - is to only emit the event when all controllers have `register`ed. We don't currently have a mechanism to track this.

**Comment by marcoroth** [comment]
I don't think this should be a big deal, since we just exported that function a few commits ago in #602. 

So it's never actually called twice unless you are explicitly importing the `setupDeclarativeReflexes()` function and calling it yourself in your application.

One solution might be to just move the `emitEvent('stimulus-reflex:ready')` to the eventlistener in `javascript/stimulus_reflex.js`:

```js
document.addEventListener('readystatechange', () => {
  if (document.readyState === 'complete') {
    setupDeclarativeReflexes()
    emitEvent('stimulus-reflex:ready')
  }
})
```

**Comment by leastbad** [comment]
> So it's never actually called twice unless you are explicitly importing the setupDeclarativeReflexes() function and calling it yourself in your application.

I don't believe that's correct. We call it every time the mutation observer picks up new elements.

https://github.com/stimulusreflex/stimulus_reflex/blob/500e6c9c5440b09c63f73bad6fad6bbdd5789f1e/javascript/stimulus_reflex.js#L64

**Comment by marcoroth** [comment]
Oh, right. But that would mean that we were also emitting the event multiple times for a long time.

**Comment by leastbad** [comment]
Yes, `stimulus-reflex:ready` is a relatively recent addition. It's possible "very few" are using it, yet.
