### ISSUE TITLE
Dependency on ActiveRecord

### ISSUE THREAD

**Issue by javierg** [stimulusreflex/stimulus_reflex#621]
We have a Rails project were ActiveRecord is absent, this project uses CouchDB as main DB and there isn't a sane AR adapter for it, so we use a simple REST adapter to talk to the DB, adding AR is not something that we have now.

past versions of stimulus reflex have been working great without this requirement, but after

https://github.com/stimulusreflex/stimulus_reflex/commit/4c52f316b5b6ac748a6c563ccfc4f1c35b52b779

The app is expecting AR to be required. I wonder if this can be optional? or it is gonna be a hard requirement? 

For now I monkey-pacthed the code that expects AR to exists, but just wonder if this will be addressed or should I think on adding AR to my project?

**Comment by leastbad** [comment]
I cannot guarantee success, but I will try to see what I can do!

**Comment by julianrubisch** [comment]
Hmmm I cannot really see how the referenced commit introduces the AR. It’s also not required in the (current) StimulusReflex and CableReady gemspecs.

What am I missing? Can you post which SR and CR versions you are running on? Thanks!

**Comment by javierg** [comment]
Sure:

Cable Ready 3.5.0.pre9
Stimulus Reflex 3.5.0.pre9

Not sure how was happening but since I don't have included AR at all in the project, and checking now the code, I don't see how it was working before, probably my code didn't reached to the updates method.

But now I get the uninitialized constant error on `ActiveRecord`, and I don't included. And I don't included, because doing so causes a bunch of side effects where a db is expected to be configured with AR.

Thanks for taking a look into this 👍

**Comment by marcoroth** [comment]
Hey @javierg, which part of StimulusReflex are you using that triggers an uninitialized constant error for `ActiveRecord`? I did setup an app without ActiveRecord but the usual stuff works even without ActiveRecord in the scope.

**Comment by marcoroth** [comment]
Oh, I see. It seems that the "uninitialized constant" error only occurs on `pre9 ` and not on `master`. Therefore, I expect that once we release `pre10` in the next few days, this issue should be resolved. Thank you for your patience and understanding as we work through this.

**Comment by marcoroth** [comment]
Hey @javierg, thanks for your patience, this should be resolved now via [`3.5.0.pre10`](https://github.com/stimulusreflex/stimulus_reflex/releases/tag/v3.5.0.pre10). Please let us know if that works for you!

**Comment by marcoroth** [comment]
Thanks for the feedback @javierg!
