### ISSUE TITLE
Installer [development] aborts under certain circumstances.

### ISSUE THREAD

**Issue by fig** [stimulusreflex/stimulus_reflex#639]
# Bug Report

## Describe the bug

The installer will abort during the [developer] task when `config.session_store` is defined and defined to other than `redis_session_store`. 

## To Reproduce

* In `config/environments/development.rb` define
```ruby
config.session_store :cache_store
```
_n.b The [Manual Configuration](https://docs.stimulusreflex.com/hello-world/setup.html#manual-configuration) still recommends `:cache_store`. Should it be changed to recommend ``redis_session_store`?_

* run the install task `rails stimulus_reflex:install`

* The [development] task will abort with
```bash
rails aborted!
NoMethodError: undefined method `match?' for #<Pathname: ...
```

## Expected behavior

The expected behavoir is for the installer to write a recommendation to `config/environments/development.rb` and append
```ruby
          # StimulusReflex recommends using Redis for session storage
          # gem "redis-session-store", "0.11.5"
```
to the `Gemfile`

### StimulusReflex

- Gem: 3.5.0.pre10
- Node package: 3.5.0.pre10

### External tools

- Ruby: 3.2.1
- Rails: 7.0.4.2
- Node: 18.14.1

## The Fix

This bug is due to the `PathName` of the Gemfile being passed to `#write_redis_recommendation` at
https://github.com/stimulusreflex/stimulus_reflex/blob/7607350bd25f29af2eb4eb7104bfc33958f1d058/lib/stimulus_reflex/installer.rb#L234
 which is expecting the actual `String` text of the Gemfile.

This method is being called with the incorrect argument from two sites:
https://github.com/stimulusreflex/stimulus_reflex/blob/7607350bd25f29af2eb4eb7104bfc33958f1d058/lib/install/development.rb#L39
https://github.com/stimulusreflex/stimulus_reflex/blob/7607350bd25f29af2eb4eb7104bfc33958f1d058/lib/install/development.rb#L45

**Comment by marcoroth** [comment]
Thanks for the detailed bug report and fix!

> The [Manual Configuration](https://docs.stimulusreflex.com/hello-world/setup.html#manual-configuration) still recommends :cache_store. Should it be changed to recommend `redis_session_store`?

Yeah, you are right! We haven't updated the Manual configuration page in the docs. The whole page needs to be updated for the new 3.5 release. I just opened #642 to rework this. Thank you!
