### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by asadakbar** [stimulusreflex/stimulus_reflex#653]
Hi is there going to a new release soon? The last one was over 2 years ago. No pressure, just wondering if the project is still active and worthwhile for new projects to integrate. Thanks for all your hard work on sr, it's been fun to learn.

**Comment by marcoroth** [comment]
Hey @asadakbar, the latest 3.5 release-candidate was releases 2 weeks ago. Please let us know if you encounter anything werid with it, thank you!
