### ISSUE TITLE
ArgumentError after upgrade stimulus_reflex and cable_ready

### ISSUE THREAD

**Issue by sFrenkie** [stimulusreflex/stimulus_reflex#656]
## Describe the bug

Rails app cannot start after upgrade stimulus_reflex to 3.5.0.rc2 (rc1, pre10 too)

## To Reproduce

Upgrade stimulus_reflex and cable_ready
from 
cable_ready (4.5.0)
stimulus_reflex (3.4.1)
to
cable_ready (5.0.0)
stimulus_reflex (3.5.0.rc2)

## Expected behavior

Run Rails with upgraded stimulus_reflex and cable_ready

## Screenshots or reproduction

`
+ bundle exec rails db:migrate
rails aborted!
ArgumentError: wrong number of arguments (given 0, expected 1)
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/stimulus_reflex-3.5.0.rc2/lib/stimulus_reflex/cable_readiness.rb:9:in `prepended'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/stimulus_reflex-3.5.0.rc2/lib/stimulus_reflex/cable_readiness.rb:9:in `<module:CableReadiness>'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/stimulus_reflex-3.5.0.rc2/lib/stimulus_reflex/cable_readiness.rb:6:in `<module:StimulusReflex>'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/stimulus_reflex-3.5.0.rc2/lib/stimulus_reflex/cable_readiness.rb:5:in `<main>'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `block in require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/stimulus_reflex-3.5.0.rc2/lib/stimulus_reflex/reflex.rb:3:in `<main>'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `block in require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/stimulus_reflex-3.5.0.rc2/lib/stimulus_reflex.rb:21:in `<main>'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `block in require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/stimulus_reflex_testing-0.3.0/lib/stimulus_reflex_testing.rb:1:in `<main>'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
/opt/mgrd/erp/config/application.rb:28:in `<main>'
/opt/mgrd/erp/Rakefile:4:in `require_relative'
/opt/mgrd/erp/Rakefile:4:in `<main>'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/command.rb:48:in `invoke'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/commands.rb:18:in `<main>'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/opt/mgrd/erp/bin/rails:9:in `<top (required)>'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/opt/mgrd/erp/vendor/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/opt/mgrd/erp/bin/spring:15:in `require'
/opt/mgrd/erp/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)
`
### StimulusReflex

- Gem: 3.5.0.pre2
- cable_ready 5.0.0

### External tools

- Ruby: 2.7
- Rails:  6.0.6

**Comment by marcoroth** [comment]
Hey @sFrenkie, thanks for reporting this!

I think this is related to the `stimulus_reflex_testing` gem.

https://github.com/podia/stimulus_reflex_testing/blob/main/lib/stimulus_reflex/test_reflex_patches.rb#L16

We changed the way cable_ready is accessed within the Reflex class in https://github.com/stimulusreflex/stimulus_reflex/commit/d493e1bfe0296a2400f5167d6c2e88c692780771

I'll try to put up a pull request for the testing gem to get this resolved!

**Comment by sFrenkie** [comment]
It seems that is not related to stimulus_reflex_testing

but in stimulus_reflex-3.5.0.rc2/lib/stimulus_reflex/cable_readiness.rb
 the block prepended expect the arguments (usualy method prepended is from core Ruby e.g. for Ruby 3.0 https://ruby-doc.org/core-3.0.0/Module.html#method-i-prepended)
I am not the autor. It should be some different method :-/

**Comment by sFrenkie** [comment]
Confirmed it's cause old rails 6.0.6 where arguments is expected https://api.rubyonrails.org/v6.0.6.1/classes/ActiveSupport/Testing/SetupAndTeardown.html#method-c-prepended

**Comment by marcoroth** [comment]
@sFrenkie Would it help if make the argument optional?

```diff
diff --git a/lib/stimulus_reflex/cable_readiness.rb b/lib/stimulus_reflex/cable_readiness.rb
index 9bb2345..14b85a9 100644
--- a/lib/stimulus_reflex/cable_readiness.rb
+++ b/lib/stimulus_reflex/cable_readiness.rb
@@ -6,7 +6,7 @@ module StimulusReflex
   module CableReadiness
     extend ActiveSupport::Concern

-    prepended do
+    prepended(mod = nil) do
       attr_reader :cable_ready
     end
```

**Comment by marcoroth** [comment]
I guess the other option would be to stop supporting Rails 6.0 with StimulusReflex 3.5

**Comment by sFrenkie** [comment]
Sorry for delay. Yeat it's better to stop supporting rails 6 ;)
I've ugpraded and it works well.
