### ISSUE TITLE
Broken Next Page Link on Welcome Page of Docs

### ISSUE THREAD

**Issue by aviflombaum** [stimulusreflex/stimulus_reflex#660]
# Bug Report

The next page link on the first page of the documentation, [Welcome](https://docs.stimulusreflex.com/hello-world/), links to the Welcome page (itself), as opposed to the correct next page, which would be [Setup](https://docs.stimulusreflex.com/hello-world/setup.html)

## To Reproduce

Go to [Welcome](https://docs.stimulusreflex.com/hello-world/) and see what happens on the Next Page click.

## Expected behavior

Going to the next page, Setup.

## Screenshots or reproduction

<img width="1286" alt="CleanShot 2023-05-25 at 10 08 19" src="https://github.com/stimulusreflex/stimulus_reflex/assets/4515/0270bf35-d901-49f7-81f2-776d4e6c247b">

I wish I knew more about vitepress so I could figure out how to fix it but looked around and nothing obvious jumped out.

<3

**Comment by marcoroth** [comment]
Hey @aviflombaum, thank you for reporting this!

Now that you mentioned it, I think I also looked into this in the past and haven't found a simple solution. It probably has to do with the different sections the pages are in, but I'm also not sure.

It might be worth to update vitepress and see if it resolves itself.

**Comment by marcoroth** [comment]
Turns out this related to the how Vitepress translates the file `hello-world/index.md` to the path `/hello-world/`.

Referencing `/hello-world/` instead of `/hello-world/index` in the Vitepress config resolves this issue. See https://github.com/stimulusreflex/stimulus_reflex/commit/3fca17501b5679ab2c982f6c9961122d002fd8e7
