### ISSUE TITLE
Reflex not triggered when a Stimulus controller is also attached to a field

### ISSUE THREAD

**Issue by cmer** [stimulusreflex/stimulus_reflex#678]
# Bug Report

## Describe the bug

Reflexes are not triggered when any other Stimulus controller is attached to an input field.

## To Reproduce

Attaching a Stimulus controller to a text field prevent reflexes from running.

## Expected behavior

The reflex should get triggered in both cases.

## Screenshots or reproduction

See: https://github.com/cmer/stimulus-reflex-bug-repro

And video demo: https://share.cleanshot.com/7sz67SPmk8sP8PGtL6xJ

### StimulusReflex

- Gem: 3.5.0.rc3
- Node package: 3.5.0.rc3

### Browser

- Browser: Any

**Comment by marcoroth** [comment]
Thanks for reporting this and for providing a repro @cmer. I was able to reproduce in the test-suite and I'm currently looking into the best way to fix it! Thanks!

**Comment by marcoroth** [comment]
This should be resolved via https://github.com/stimulusreflex/stimulus_reflex/pull/670

**Comment by cmer** [comment]
Thank you SO MUCH! Awesome!!! Can't wait to give it a shot. You have a typo, btw. Left a comment.

**Comment by marcoroth** [comment]
This should be resolved with the release of [`v3.5.0.rc4`](https://github.com/stimulusreflex/stimulus_reflex/releases/tag/v3.5.0.rc4). I'm going to close this issue, but please feel free to re-open if you are still see something unexpected!
