### ISSUE TITLE
OpenStruct no longer supported by json

### ISSUE THREAD

**Issue by TanookiMario** [stimulusreflex/stimulus_reflex#695]
# Bug Report

## Describe the bug

[Rubocop v1.63.0](https://github.com/rubocop/rubocop/releases/tag/v1.63.0) updates [json to v2.7.2](https://github.com/flori/json/releases/tag/v2.7.2). `json` v2.7.2 [makes OpenStruct optional](https://github.com/flori/json/pull/565). `StimulusReflex` relies on `OpenStruct` in both the [Dataset](https://github.com/stimulusreflex/stimulus_reflex/blob/3a5111e085b21d1e628813e2cee72e978acb257a/lib/stimulus_reflex/dataset.rb#L5) and the [Element](https://github.com/stimulusreflex/stimulus_reflex/blob/3a5111e085b21d1e628813e2cee72e978acb257a/lib/stimulus_reflex/element.rb#L6) models. Attempting to run rails, ie a `rails console`, results in the error

```
/.rvm/gems/ruby-3.2.2/gems/stimulus_reflex-3.5.0.rc4/lib/stimulus_reflex/dataset.rb:5:in `<main>': uninitialized constant OpenStruct (NameError)
```

## To Reproduce

using `rubocop v1.63.0` or above, attempt to run rails console or start a rails server

## Expected behavior

the rails action can be performed without an error that causes it to exit

it seems a quick fix would be to explicitly requiring `ostruct`, like [this suggestion](https://github.com/flori/json/issues/579)

a longer term fix would be to stop using `OpenStruct` altogether as its [use is discouraged](https://github.com/ruby/ostruct/blob/master/lib/ostruct.rb#L136)

### StimulusReflex

- Gem: `3.5.0.rc4`
- Node package: `yarn 1.22.19`

### External tools

- Ruby: `3.2.2p53`
- Rails: `7.0.8.1`
- Node: `18.19.0`
- Rubocop: `1.63.0`
- Json: `2.7.2`

**Comment by marcoroth** [comment]
Thanks for reporting @TanookiMario, I put up #697 to address this!
