### ISSUE TITLE
Unrecognized command "esbuild" (Rails::Command::UnrecognizedCommandError)

### ISSUE THREAD

**Issue by la-ruby** [stimulusreflex/stimulus_reflex#708]
The  documentation and the --help mentions this esbuild  option but it throws an error

## To Reproduce

$ rails stimulus_reflex:install esbuild
Unrecognized command "esbuild" (Rails::Command::UnrecognizedCommandError)
Did you mean?  css:build

### StimulusReflex

- Gem:3.5.2 (tried main too)
- Node package: 3.5.2

### External tools

- Ruby: 3.3.0
- Rails: github => 'rails/rails', :branch => '7-1-stable'
- Node: 21.7.2

**Comment by marcoroth** [comment]
Hey @la-ruby, thanks for reporting.

We removed the explicit option for the installer in 3.5.0, I just updated the docs to reflect that in https://github.com/stimulusreflex/stimulus_reflex/commit/6851a630ffa7084fc4eec43599f25a4701ef78f0.

Thank you!
