### ISSUE TITLE
Compability with Ruby on Rails 8

### ISSUE THREAD

**Issue by rodrigotoledo** [stimulusreflex/stimulus_reflex#722]
# Bug Report

Maybe this isn't a bug, but I was trying to demonstrate how this gem works to my friend. My project is using Ruby on Rails 8, and nothing happens when I try to show it. Maybe it's a bug with the new version. Shall we take a look?

## Describe the bug

I install the gem, set up, then create the reflex class and add a method to render a partial.

## To Reproduce

When I create the button with an action calling my reflex class and method, nothing happens.

## Expected behavior

In Rails version 7, the reflex class is called and the morph method is invoked.

### StimulusReflex

- Gem: 3.5

**Comment by JuanMiguelGM** [comment]
Hi, are there any intentions to support Rails 8?

**Comment by pacso** [comment]
The lack of support for Rails 8, and the extremely slow response here has been enough for us to make the jump away from Stimulus Reflex.

**Comment by sara-g** [comment]
I got this to work in Rails 8, I put in a PR.

**Comment by marcoroth** [comment]
Just merged #726 and going to follow up with a v3.5.2 release shortly! :raised_hands:

Please feel free to re-open if you see any other issue with Rails 8, thank you!
